version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: vote_meeting_mongo
    restart: unless-stopped

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE:      vote_for_meeting 

    volumes:
      - mongo_data:/data/db
      - ./init:/docker-entrypoint-initdb.d:ro 

    ports:
      - "27017:27017" 

volumes:
  mongo_data:
